name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: sudo apt-get -y install autoconf-archive libell-dev pandoc
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      # The kernel in Ubuntu 20.04 doesn't support MPTCP.  Expect failures.
      run: make check XFAIL_TESTS="test-commands test-path-manager test-start-stop"
    - name: make distcheck
      run: make distcheck XFAIL_TESTS="test-commands test-path-manager test-start-stop"
    - name: make installcheck
      run: sudo make installcheck
